# Generated by Django 4.2.2 on 2023-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerapp', '0002_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Mid'), (3, 'High')], verbose_name='Category'),
        ),
    ]
