# Generated by Django 4.2.2 on 2023-06-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerapp', '0003_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Nike'), (2, 'Addidas Originals'), (3, 'Converse'), (4, 'Puma'), (5, 'Fila'), (6, 'Vans'), (7, 'Asics'), (8, 'New Balance')], verbose_name='Brand'),
        ),
    ]
